### PR TITLE
[RTM] Fix duplicate alias check

### PR DESCRIPTION
**Pull request by ausi**
This should fix #18

### CODE REVIEW

**Comment by patrickjDE** [comment]
It won't. You'd still be able to manually enter a duplicate alias.

**Comment by ausi** [comment]
I copied the code from `tl_page`, but I think you are right. We would have to exclude the current ID in the database query.

**Comment by ausi** [comment]
@patrickjDE I think it should work now.

**Comment by leofeyer** [comment]
Thank you @ausi.

**Pull request merged**
